package com.etendoerp.jars.modules

import com.etendoerp.jars.PathUtils
import com.etendoerp.jars.Utils
import org.gradle.api.Project

class ModuleJarUtils {

    /**
     * Filters the 'javaClassesFiles' passed has parameters, only returning the ones
     * that are not autogenerated.
     * The 'javaClassesFiles' should contain java classes following the format 'package/path/ClassName.class'
     * Ex: 'com/etendoerp/test/CustomClassName.class'
     * @param project
     * @param javaClassesFiles
     * @return
     */
    static List<String> filterAutogeneratedClasses(Project project, List<String> javaClassesFiles) {
        List<String> filteredList = new ArrayList<>()

        for (String fullPath : javaClassesFiles) {
            String packagePath = PathUtils.fromPathWithClassToPackageFormat(fullPath)

            // The java class is not autogenerated
            if (!Utils.existGeneratedClass(packagePath,project)){
                filteredList.add(fullPath)
            }
        }

        return filteredList
    }

    /**
     * Loads the module name passed by the command line as a parameter.
     * @param project
     * @return
     */
    static String loadModuleName(Project project) {
        String moduleName = project.findProperty(ModuleJarLoader.MODULE_NAME_PROP)

        if (moduleName == null || moduleName.isBlank()) {
            throw new IllegalArgumentException("The command line parameter -P${ModuleJarLoader.MODULE_NAME_PROP}=<module name> is missing.")
        }
        return moduleName
    }

}
